### ISSUE TITLE
starting with icecast in fails autotee.IcecastUrls-conversion

### ISSUE THREAD

**Issue by MaZderMind** [fxkr/autotee#24]
````
---
  # Alternatively:
  url: "http://live.ber.c3voc.de:8000/status-json.xsl"
  type: "icecast"
````

````
voc@minion5:~/music-transcoding$ autotee music-config.yml                                                                                                                                      2016-12-27 17:49:49
WARN[17:49:54] New stream                                    match=true stream="ambient_lounge.opus"
WARN[17:49:54] New stream                                    match=true stream="chaoswest_lounge.ogg"
panic: interface conversion: mapset.Set is autotee.IcecastUrls, not *mapset.threadSafeSet

goroutine 1 [running]:
panic(0x791cc0, 0xc4201661c0)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a1
github.com/deckarep/golang-set.(*threadSafeSet).Difference(0xc4200d35a0, 0x994e40, 0xc420142890, 0xc42010f900, 0xc42013c7c0)
	/home/anton/Projects/go/src/github.com/deckarep/golang-set/threadsafe.go:96 +0x192
github.com/fxkr/autotee/src.(*App).Run(0xc420013c20, 0xc4200103d0, 0xc4200ac420)
	/home/anton/Projects/go/src/github.com/fxkr/autotee/src/app.go:88 +0x83f
github.com/fxkr/autotee/src.Main.func1(0xc42009a640, 0xc42009a640, 0xc42004db87)
	/home/anton/Projects/go/src/github.com/fxkr/autotee/src/main.go:73 +0x242
github.com/codegangsta/cli.HandleAction(0x77e940, 0xc4200d2c00, 0xc42009a640, 0x0, 0x0)
	/home/anton/Projects/go/src/github.com/codegangsta/cli/app.go:485 +0xd4
github.com/codegangsta/cli.(*App).Run(0xc42007f860, 0xc42000c400, 0x2, 0x2, 0x0, 0x0)
	/home/anton/Projects/go/src/github.com/codegangsta/cli/app.go:259 +0x74f
github.com/fxkr/autotee/src.Main()
	/home/anton/Projects/go/src/github.com/fxkr/autotee/src/main.go:77 +0x3a3
main.main()
	/home/anton/Projects/go/src/github.com/fxkr/autotee/autotee.go:6 +0x14
````

**Comment by fxkr** [comment]
Thanks for the bugreport; sorry I broke that. Here's the fix.
